
const S={protocols:[],meds:[],pcards:[],scenarios:[],dcards:[],tab:'home',mode:'mixed',queue:[],idx:0,show:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ls={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const favs=()=>new Set(ls.get('favorites',[]));
function toggleFav(id){let f=favs();f.has(id)?f.delete(id):f.add(id);ls.set('favorites',[...f]);render();}
function stats(){return ls.get('stats',{correct:0,wrong:0,reviewed:0,streak:0,last:'',history:{}})}
function record(id,ok){let st=stats();st.reviewed++;ok?st.correct++:st.wrong++;let d=new Date().toISOString().slice(0,10);if(st.last!==d){let y=new Date(Date.now()-864e5).toISOString().slice(0,10);st.streak=st.last===y?st.streak+1:1;st.last=d}let h=st.history[id]||{ease:2.5,interval:0,due:0};if(ok){h.interval=h.interval===0?1:h.interval===1?3:Math.round(h.interval*h.ease);h.ease=Math.min(3,h.ease+.05)}else{h.interval=0;h.ease=Math.max(1.3,h.ease-.2)}h.due=Date.now()+h.interval*864e5;st.history[id]=h;ls.set('stats',st)}
function dueCount(){let st=stats(),now=Date.now();return [...S.dcards,...S.pcards,...S.scenarios].filter(c=>(st.history[c.id]?.due||0)<=now).length}
async function load(){let [p,m,pc,sc,dc]=await Promise.all(['protocols','medications','protocol_cards','scenarios','dose_cards'].map(n=>fetch(`data/${n}.json`).then(r=>r.json())));Object.assign(S,{protocols:p,meds:m,pcards:pc,scenarios:sc,dcards:dc});render()}
function nav(){ $$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab)); }
function setTab(t){S.tab=t;render();scrollTo(0,0)}
function home(){let st=stats(),acc=st.reviewed?Math.round(st.correct/st.reviewed*100):0;return `<section class="hero"><h2>Know the protocol.</h2><p>Search the full education draft, memorize medications and doses, and review what you miss.</p></section><div class="stats"><div class="stat"><b>${dueCount()}</b><span>Due now</span></div><div class="stat"><b>${acc}%</b><span>Accuracy</span></div><div class="stat"><b>${st.streak}</b><span>Day streak</span></div></div><h2 class="sectionTitle">Quick study</h2><div class="grid"><button class="action" onclick="startStudy('due')">Due cards<small>Spaced repetition review</small></button><button class="action" onclick="startStudy('dose')">Dose drill<small>Medication dosing only</small></button><button class="action" onclick="startStudy('protocol')">Protocols<small>Recall treatment steps</small></button><button class="action" onclick="startStudy('recognition')">Recognition<small>Name the protocol</small></button></div><h2 class="sectionTitle">Library</h2><div class="grid"><button class="action" onclick="setTab('protocols')">${S.protocols.length} protocols<small>Search all sections</small></button><button class="action" onclick="setTab('meds')">${S.meds.length} medications<small>Indications, doses & notes</small></button></div>`}
function protocolList(){let cats=['All',...new Set(S.protocols.map(x=>x.category))];return `<input id="q" class="search" placeholder="Search protocols…" oninput="filterProtocols()"><div class="chips" id="pcats">${cats.map((c,i)=>`<button class="chip ${i?'':'active'}" onclick="pickPCat(this,'${esc(c).replace(/'/g,"\\'")}')">${esc(c)}</button>`).join('')}</div><div id="plist" class="list">${protoRows(S.protocols)}</div>`}
function protoRows(a){return a.map(p=>`<button class="row" onclick="openProtocol('${p.id}')"><span class="num">${esc(p.number)} · ${esc(p.category)}</span><h3>${esc(p.title)}</h3><p>Source pp. ${p.startPage}${p.endPage&&p.endPage!==p.startPage?'–'+p.endPage:''}</p></button>`).join('')}
let pcat='All';function pickPCat(el,c){pcat=c;$$('#pcats .chip').forEach(x=>x.classList.remove('active'));el.classList.add('active');filterProtocols()}
function filterProtocols(){let q=($('#q')?.value||'').toLowerCase();let a=S.protocols.filter(p=>(pcat==='All'||p.category===pcat)&&(`${p.number} ${p.title} ${p.body}`.toLowerCase().includes(q)));$('#plist').innerHTML=protoRows(a)}
function medsList(){return `<input id="mq" class="search" placeholder="Search medications…" oninput="filterMeds()"><div id="mlist" class="list">${medRows(S.meds)}</div>`}
function medRows(a){let f=favs();return a.map(m=>`<button class="row" onclick="openMed('${m.id}')"><span class="num">${esc(m.protocolNumber)} ${f.has('m:'+m.id)?'★':''}</span><h3>${esc(m.name)}</h3><p>${esc(m.routes.join(' · '))}</p></button>`).join('')}
function filterMeds(){let q=($('#mq')?.value||'').toLowerCase();$('#mlist').innerHTML=medRows(S.meds.filter(m=>JSON.stringify(m).toLowerCase().includes(q)))}
function listBlock(title,arr){return arr?.length?`<div class="block"><h3>${title}</h3>${arr.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div>`:''}
function openMed(id){let m=S.meds.find(x=>x.id===id),f=favs().has('m:'+id);modal(`<div class="detail"><button class="fav" onclick="toggleFav('m:${id}');openMed('${id}')">${f?'★':'☆'}</button><span class="num">${esc(m.protocolNumber)}</span><h2>${esc(m.name)}</h2><div class="meta">Education draft · source page ${m.sourcePage}</div>${listBlock('Class',m.drugClass)}${listBlock('Routes',m.routes)}${listBlock('Indications',m.indications)}${listBlock('Contraindications',m.contraindications)}<div class="block"><h3>Administration / dosing</h3><div class="bodyText">${esc(m.administrationText)}</div></div>${listBlock('Special notes',m.specialNotes)}</div>`)}
function openProtocol(id){let p=S.protocols.find(x=>x.id===id),f=favs().has('p:'+id);modal(`<div class="detail"><button class="fav" onclick="toggleFav('p:${id}');openProtocol('${id}')">${f?'★':'☆'}</button><span class="num">${esc(p.number)} · ${esc(p.category)}</span><h2>${esc(p.title)}</h2><div class="meta">Education draft · source pp. ${p.startPage}${p.endPage!==p.startPage?'–'+p.endPage:''}</div>${p.designation?`<div class="block"><h3>Designation / overview</h3><div class="bodyText">${esc(p.designation)}</div></div>`:''}<div class="block"><h3>Protocol text</h3><div class="bodyText">${esc(p.body)}</div></div></div>`)}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function makeQueue(mode){let arr;if(mode==='dose')arr=S.dcards.map(c=>({...c,type:'Dose'}));else if(mode==='protocol')arr=S.pcards.map(c=>({...c,type:'Protocol'}));else if(mode==='recognition')arr=S.scenarios.map(c=>({...c,type:'Recognition'}));else if(mode==='due'){let now=Date.now(),st=stats();arr=[...S.dcards.map(c=>({...c,type:'Dose'})),...S.pcards.map(c=>({...c,type:'Protocol'})),...S.scenarios.map(c=>({...c,type:'Recognition'}))].filter(c=>(st.history[c.id]?.due||0)<=now)}else arr=[...S.dcards.map(c=>({...c,type:'Dose'})),...S.pcards.map(c=>({...c,type:'Protocol'})),...S.scenarios.map(c=>({...c,type:'Recognition'}))];return arr.sort(()=>Math.random()-.5).slice(0,30)}
function startStudy(mode){S.mode=mode;S.queue=makeQueue(mode);S.idx=0;S.show=false;S.tab='study';render()}
function study(){if(!S.queue.length)return `<h2>Study</h2><div class="card"><p>Choose a study mode.</p><div class="grid"><button class="action" onclick="startStudy('due')">Due</button><button class="action" onclick="startStudy('dose')">Dose drill</button><button class="action" onclick="startStudy('protocol')">Protocols</button><button class="action" onclick="startStudy('recognition')">Recognition</button><button class="action" onclick="startStudy('mixed')">Mixed 30</button></div></div>`;let c=S.queue[S.idx];if(!c)return `<div class="card"><h2>Session complete</h2><p>Nice work. Your results were saved on this device.</p><button class="btn primary" onclick="startStudy('${S.mode}')">Study again</button></div>`;return `<div class="metric"><b>${esc(c.type)}</b><span>${S.idx+1}/${S.queue.length}</span></div><div class="progress"><div style="width:${(S.idx+1)/S.queue.length*100}%"></div></div><div style="height:12px"></div><section class="studyCard"><div><div class="label">Question</div><h2>${esc(c.prompt)}</h2><div class="answer ${S.show?'':'hiddenAnswer'}">${esc(c.answer)}</div></div>${S.show?`<div class="buttons"><button class="btn bad" onclick="grade(false)">Missed it</button><button class="btn good" onclick="grade(true)">Got it</button></div>`:`<button class="btn primary" onclick="S.show=true;render()">Show answer</button>`}</section>`}
function grade(ok){let c=S.queue[S.idx];record(c.id,ok);S.idx++;S.show=false;render()}
function more(){let st=stats(),total=st.reviewed,acc=total?Math.round(st.correct/total*100):0,f=favs();return `<h2>Progress</h2><div class="card"><div class="metric"><span>Cards reviewed</span><b>${total}</b></div><div class="metric"><span>Correct</span><b>${st.correct}</b></div><div class="metric"><span>Accuracy</span><b>${acc}%</b></div><div class="metric"><span>Current streak</span><b>${st.streak} days</b></div></div><h2 class="sectionTitle">Favorites</h2><div class="card"><p>${[...f].length} saved items</p><button class="btn primary" onclick="showFavorites()">View favorites</button></div><h2 class="sectionTitle">Dose calculator practice</h2><div class="card"><label>Weight (lb)</label><input id="lbs" class="search" inputmode="decimal" placeholder="e.g. 44" oninput="calcKg()"><p id="kg">Enter a weight to convert to kg.</p></div><h2 class="sectionTitle">About</h2><div class="card bodyText">This app is a study aid built from the uploaded Snohomish County EMS V7 education draft. It is not an approved clinical reference and should not be used for patient care. Study progress and favorites are stored only on this device.</div>`}
function calcKg(){let x=parseFloat($('#lbs').value);$('#kg').textContent=isFinite(x)?`${(x/2.2046226218).toFixed(1)} kg`:'Enter a weight to convert to kg.'}
function showFavorites(){let f=favs(),p=S.protocols.filter(x=>f.has('p:'+x.id)),m=S.meds.filter(x=>f.has('m:'+x.id));modal(`<div class="detail"><h2>Favorites</h2><h3 class="sectionTitle">Protocols</h3><div class="list">${protoRows(p)||'<p>None yet.</p>'}</div><h3 class="sectionTitle">Medications</h3><div class="list">${medRows(m)||'<p>None yet.</p>'}</div></div>`)}
function render(){nav();let v=S.tab==='home'?home():S.tab==='protocols'?protocolList():S.tab==='meds'?medsList():S.tab==='study'?study():more();$('#main').innerHTML=v;nav()}
$$('#tabs button').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
window.setTab=setTab;window.startStudy=startStudy;window.filterProtocols=filterProtocols;window.pickPCat=pickPCat;window.openProtocol=openProtocol;window.openMed=openMed;window.toggleFav=toggleFav;window.filterMeds=filterMeds;window.grade=grade;window.showFavorites=showFavorites;window.calcKg=calcKg;window.S=S;
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}else alert('On iPhone: tap Share in Safari, then Add to Home Screen.')};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
load().catch(e=>{$('#main').innerHTML=`<div class="card"><h2>Could not load app data</h2><p>${esc(e.message)}</p><p>This app must be opened from a web server (HTTPS) rather than directly as a local file.</p></div>`});
